name: Auto Post to Telegram Channel

on:
  schedule:
    - cron: '0 * * * *'  # Каждый час
  workflow_dispatch:     # Ручной запуск

jobs:
  post-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4   # лучше использовать v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'   # свежая версия

      - name: Install Dependencies
        run: |
          pip install requests
          pip install huggingface_hub   # главная библиотека

      - name: Run Bot
        env:
          HF_API_TOKEN: ${{ secrets.HF_API_TOKEN }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: python bot.py
